# Generated by Django 2.2 on 2021-04-18 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Phone', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Number', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')])),
                ('URLField', models.URLField()),
            ],
        ),
    ]
